[phases.setup]
nixPkgs = ["php", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx",
    "mkdir -p /var/cache/nginx",
    "composer install --ignore-platform-reqs --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"

[build.args]
PHP_VERSION = "8.2"
NODE_VERSION = "18"

[build.env]
NODE_ENV = "production"
APP_ENV = "production"
APP_DEBUG = "false"